name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt -- --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
      - uses: taiki-e/install-action@cargo-hack
      - name: clippy
        run: cargo hack clippy --feature-powerset --no-dev-deps --exclude-features default-layout-any-buffer,default-layout-static,default-layout-boxed-slice,default-layout-raw,default-layout-vec,default-layout-mut-any-buffer,default-layout-vec --depth 2 -- -D warnings
      - name: doc
        run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings
      - name: expect
        run: git grep -lz "#\[allow" | xargs -0 sed -i "s/#\[allow(/#[expect(/g" && cargo clippy --all-features
  unreachable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layout: [boxed-slice, vec, raw, mut-vec]
    steps:
      - name: unreachable_unchecked
        run: cargo build --manifest-path=bytes/Cargo.toml --tests --release --features=default-layout-${{ matrix.layout }}
        env:
          RUSTFLAGS: --cfg=unreachable_checked
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: cargo test --all-features
      - name: install miri
        run: rustup install nightly && rustup +nightly component add miri
      - name: miri
        run: cargo +nightly miri test --all-features
      - name: miri many-seeds
        run: cargo +nightly miri test --test concurrency
        env:
          MIRIFLAGS: -Zmiri-many-seeds
      - name: miri bytes
        run: cargo +nightly miri test --manifest-path=bytes/Cargo.toml --test test_bytes
